components: 
  schemas: 
    Currency: 
      additionalProperties: false
      properties: 
        date: 
          format: date-time
          readOnly: true
          type: string
        details: 
          $ref: "#/components/schemas/CurrencyDetail"
        pretty: 
          nullable: true
          type: string
        value: 
          format: double
          type: number
      type: object
    CurrencyDetail: 
      additionalProperties: false
      properties: 
        isVirtual: 
          type: boolean
        iso: 
          nullable: true
          type: string
        name: 
          nullable: true
          type: string
        symbol: 
          nullable: true
          type: string
      type: object
info: 
  title: currency_tracker
  version: v1
openapi: "3.0.1"
paths: 
  /Currency/currencies: 
    get: 
      parameters: 
        - 
          in: query
          name: iso
          schema: 
            nullable: true
            type: string
      responses: 
        ? "200"
        : 
          content: 
            application/json: 
              schema: 
                items: 
                  $ref: "#/components/schemas/Currency"
                type: array
            text/json: 
              schema: 
                items: 
                  $ref: "#/components/schemas/Currency"
                type: array
            text/plain: 
              schema: 
                items: 
                  $ref: "#/components/schemas/Currency"
                type: array
          description: Success
      tags: 
        - Currency
  ? "/Currency/currencies/{iso}"
  : 
    get: 
      parameters: 
        - 
          in: path
          name: iso
          required: true
          schema: 
            nullable: true
            type: string
      responses: 
        ? "200"
        : 
          content: 
            application/json: 
              schema: 
                $ref: "#/components/schemas/Currency"
            text/json: 
              schema: 
                $ref: "#/components/schemas/Currency"
            text/plain: 
              schema: 
                $ref: "#/components/schemas/Currency"
          description: Success
      tags: 
        - Currency
  /Currency/currency/all: 
    get: 
      parameters: 
        - 
          in: query
          name: iso
          schema: 
            nullable: true
            type: string
      responses: 
        ? "200"
        : 
          content: 
            application/json: 
              schema: 
                items: 
                  $ref: "#/components/schemas/Currency"
                type: array
            text/json: 
              schema: 
                items: 
                  $ref: "#/components/schemas/Currency"
                type: array
            text/plain: 
              schema: 
                items: 
                  $ref: "#/components/schemas/Currency"
                type: array
          description: Success
      tags: 
        - Currency
  ? "/Currency/currency/all/{iso}"
  : 
    get: 
      parameters: 
        - 
          in: path
          name: iso
          required: true
          schema: 
            nullable: true
            type: string
      responses: 
        ? "200"
        : 
          content: 
            application/json: 
              schema: 
                $ref: "#/components/schemas/Currency"
            text/json: 
              schema: 
                $ref: "#/components/schemas/Currency"
            text/plain: 
              schema: 
                $ref: "#/components/schemas/Currency"
          description: Success
      tags: 
        - Currency
  ? "/Currency/ratio/{iso1}/{iso2}"
  : 
    get: 
      parameters: 
        - 
          in: path
          name: iso1
          required: true
          schema: 
            nullable: true
            type: string
        - 
          in: path
          name: iso2
          required: true
          schema: 
            nullable: true
            type: string
      responses: 
        ? "200"
        : 
          content: 
            application/json: 
              schema: 
                type: string
            text/json: 
              schema: 
                type: string
            text/plain: 
              schema: 
                type: string
          description: Success
      tags: 
        - Currency