openapi: 3.0.1
info:
  title: currency_tracker
  version: v1
paths:
  /Currency:
    get:
      tags:
        - Currency
      parameters:
        - name: iso
          in: query
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Currency'
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Currency'
            text/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Currency'
  /Currency/all:
    get:
      tags:
        - Currency
      parameters:
        - name: iso
          in: query
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Currency'
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Currency'
            text/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Currency'
  '/Currency/{iso}':
    get:
      tags:
        - Currency
      parameters:
        - name: iso
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/Currency'
            application/json:
              schema:
                $ref: '#/components/schemas/Currency'
            text/json:
              schema:
                $ref: '#/components/schemas/Currency'
  '/Currency/ratio/{iso1}/{iso2}':
    get:
      tags:
        - Currency
      parameters:
        - name: iso1
          in: path
          required: true
          schema:
            type: string
        - name: iso2
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/CurrencyRatios'
            application/json:
              schema:
                $ref: '#/components/schemas/CurrencyRatios'
            text/json:
              schema:
                $ref: '#/components/schemas/CurrencyRatios'
components:
  schemas:
    Currency:
      type: object
      properties:
        details:
          $ref: '#/components/schemas/CurrencyDetail'
        date:
          type: string
          format: date-time
        value:
          type: number
          format: double
        pretty:
          type: string
          nullable: true
          readOnly: true
      additionalProperties: false
    CurrencyDetail:
      type: object
      properties:
        iso:
          type: string
          nullable: true
        name:
          type: string
          nullable: true
        symbol:
          type: string
          nullable: true
        isVirtual:
          type: boolean
      additionalProperties: false
    CurrencyRatios:
      type: object
      properties:
        from:
          type: number
          format: double
        to:
          type: number
          format: double
        ratio:
          type: string
          nullable: true
        fromCurrency:
          $ref: '#/components/schemas/Currency'
        toCurrency:
          $ref: '#/components/schemas/Currency'
      additionalProperties: false